backend:
  name: github
  repo: leadanalystlabs/leadanalystlabs
  branch: main
  base_url: https://auth.leadanalystlabs.com
  auth_endpoint: auth

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish date"
        name: "date"
        widget: "datetime"
      - label: "Featured image"
        name: "image"
        widget: "image"
        required: false
      - label: "Summary"
        name: "description"
        widget: "text"
        required: false
      - label: "Post body"
        name: "body"
        widget: "markdown"
